
package dulcegalleta;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaimiko
 */
public class REmpleados extends javax.swing.JFrame {

    /**
     * Creates new form REmpleados
     */
    public REmpleados() {
        initComponents();
        
    }
     RVentas ventas_up = new RVentas();
    ArrayList<empleados> empleado = new ArrayList<>();
    String xRut ="", xDv = "",nombre ="", apellido="",direccion="",telefono="",mail="";
    
    empleados emp1 = new empleados("184346494","maria antonieta","de las nieves","La vecindad","56543456","maria@correo.cl");
    empleados emp2 = new empleados("244204562","Julieta","venegas","guanajuato 133","98745621","julieta@correo.cl");
    empleados emp3 = new empleados("267896491","Lady","gaga","eeuu 551","133133654","gaga@correo.cl");
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jT_Nombre = new javax.swing.JTextField();
        jT_apellido = new javax.swing.JTextField();
        jT_direccion = new javax.swing.JTextField();
        jT_Telefono = new javax.swing.JTextField();
        jT_Mail = new javax.swing.JTextField();
        jT_Rut = new javax.swing.JTextField();
        jB_RegisEmp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jT_DV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registro de empleados");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("RUT :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("NOMBRE :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setText("TELEFONO :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setText("DIRECCION :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setText("APELLIDO :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setText("CORREO :");

        jT_Nombre.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jT_Nombre.setEnabled(false);
        jT_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NombreActionPerformed(evt);
            }
        });
        jT_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_NombreKeyReleased(evt);
            }
        });

        jT_apellido.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jT_apellido.setEnabled(false);
        jT_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_apellidoActionPerformed(evt);
            }
        });
        jT_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_apellidoKeyReleased(evt);
            }
        });

        jT_direccion.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jT_direccion.setEnabled(false);
        jT_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_direccionActionPerformed(evt);
            }
        });
        jT_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_direccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jT_direccionKeyTyped(evt);
            }
        });

        jT_Telefono.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jT_Telefono.setEnabled(false);
        jT_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_TelefonoActionPerformed(evt);
            }
        });
        jT_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_TelefonoKeyReleased(evt);
            }
        });

        jT_Mail.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jT_Mail.setEnabled(false);
        jT_Mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_MailActionPerformed(evt);
            }
        });
        jT_Mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_MailKeyReleased(evt);
            }
        });

        jT_Rut.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jT_Rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_RutActionPerformed(evt);
            }
        });
        jT_Rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_RutKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_RutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jT_RutKeyTyped(evt);
            }
        });

        jB_RegisEmp.setBackground(new java.awt.Color(204, 204, 204));
        jB_RegisEmp.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jB_RegisEmp.setText("GUARDAR");
        jB_RegisEmp.setEnabled(false);
        jB_RegisEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RegisEmpActionPerformed(evt);
            }
        });
        jB_RegisEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jB_RegisEmpKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dulcegalleta/Recursos/flecha-izquierda22.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jT_DV.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jT_DV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_DVActionPerformed(evt);
            }
        });
        jT_DV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_DVKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_DVKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jT_DVKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setText("-");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jT_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jT_DV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jB_RegisEmp)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jT_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_DV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jT_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jT_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jT_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_RegisEmp)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jT_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NombreActionPerformed

    private void jT_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_apellidoActionPerformed

    private void jT_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_direccionActionPerformed

    private void jT_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_TelefonoActionPerformed

    private void jT_MailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_MailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_MailActionPerformed

    private void jT_RutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_RutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_RutActionPerformed

    private void jT_RutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_RutKeyTyped
        // TODO add your handling code here:
        //String xRut ="";
        //xRut = jTextField7.getText();
    }//GEN-LAST:event_jT_RutKeyTyped

    private void jT_RutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_RutKeyPressed
  
    }//GEN-LAST:event_jT_RutKeyPressed

    private void jT_DVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_DVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_DVActionPerformed

    private void jT_DVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_DVKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_DVKeyPressed

    private void jT_DVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_DVKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_DVKeyTyped

    private void jT_RutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_RutKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!"".equals(jT_Rut.getText())){
                
                jT_DV.requestFocus();
            }
        }
    }//GEN-LAST:event_jT_RutKeyReleased

    private void jT_DVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_DVKeyReleased
               
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            xRut = jT_Rut.getText();
            xDv = jT_DV.getText();
            if(isValidRut(xRut+ xDv)){ 
                    if (VerificaEmpleado(xRut+ xDv)){
                        jT_Rut.setText("");
                        jT_DV.setText("");
                        jT_Rut.requestFocus();
                    } else{
                        jT_Nombre.setEnabled(true);
                        jT_Nombre.requestFocus();
                    }
                
                
               // Mensaje("Rut Valido");
               
            }else{
                Mensaje("Rut invalido");
                xRut = "";
            }
        } 
    }//GEN-LAST:event_jT_DVKeyReleased

    private void jT_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_NombreKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jT_Nombre.getText() != null){
                nombre = jT_Nombre.getText();
                jT_apellido.setEnabled(true);
                jT_apellido.requestFocus();
            }
        } 
    }//GEN-LAST:event_jT_NombreKeyReleased

    private void jT_apellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_apellidoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jT_apellido.getText() != null){
                apellido = jT_apellido.getText();
                jT_direccion.setEnabled(true);
                jT_direccion.requestFocus();
            }
        }
    }//GEN-LAST:event_jT_apellidoKeyReleased

    private void jT_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_direccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_direccionKeyTyped

    private void jT_direccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_direccionKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jT_direccion.getText() != null){
                direccion = jT_direccion.getText();
                jT_Telefono.setEnabled(true);
                jT_Telefono.requestFocus();
            }
        }
    }//GEN-LAST:event_jT_direccionKeyReleased

    private void jT_TelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_TelefonoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jT_Telefono.getText() != null){
                telefono = jT_Telefono.getText();
                jT_Mail.setEnabled(true);
                jT_Mail.requestFocus();
            }
        }
    }//GEN-LAST:event_jT_TelefonoKeyReleased

    private void jT_MailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_MailKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(jT_Mail.getText() != null){
                mail = jT_Mail.getText();
                jB_RegisEmp.setEnabled(true);
                jB_RegisEmp.requestFocus();
            }
        }
    }//GEN-LAST:event_jT_MailKeyReleased

    private void jB_RegisEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RegisEmpActionPerformed
      Mensaje("Empleado agregado \n satisfactoriamente");
      Limpia();
    }//GEN-LAST:event_jB_RegisEmpActionPerformed

    private void jB_RegisEmpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jB_RegisEmpKeyReleased
    
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            empleados emp = new empleados(xRut +xDv ,nombre, apellido,direccion,telefono,mail);
            empleado.add(emp);
            Mensaje("Empleado agregado \n satisfactoriamente");
            Limpia();
        }
    }//GEN-LAST:event_jB_RegisEmpKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        cargaEmpleados();
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        MuestraAlumos();
        System.exit(0);
        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REmpleados().setVisible(true);
                            }
        });
        
        
    }
 
    
    private boolean isValidRut(String rut)
    {
        boolean ret = false;
        if(rut != null && rut.trim().length() > 0)
        {
            try {
                rut = rut.replaceAll("[.]", "").replaceAll("-", "").trim().toUpperCase();
                char dv = rut.charAt(rut.length() - 1);
                String mantisa = rut.substring(0, rut.length() - 1);
                if( isInteger( mantisa ) )
                {
                    int mantisaInt = Integer.parseInt( mantisa );
                    ret = validarRut( mantisaInt, dv ) ;
                }
            }
            catch (Throwable e) 
            {
                error("[isValidRut] ["+rut+"]", e);
            }
        }
        return ret;
    }

    private boolean validarRut(int rut, char dv)
    {
        int m = 0, s = 1;
        for (; rut != 0; rut /= 10)
        {
            s = (s + rut % 10 * (9 - m++ % 6)) % 11;

        }
        return Character.toUpperCase(dv) == (char) (s != 0 ? s + 47 : 75) ;
    }

    public boolean isInteger(String cad)
    {
        for(int i = 0; i<cad.length(); i++){
            if( !Character.isDigit(cad.charAt(i)) )
            {
                return false;
            }
        }
        return true;

    }
    
    public boolean VerificaEmpleado(String xRut){
        boolean encontrado = false;
       // if(!empleado.isEmpty()){
            
          //  empleados em = new empleados();
            String nomb ="";
            
            for (int x = 0 ; x <= empleado.size()-1; x++) {
                   String p = empleado.get(x).getRut();
                    if (p.equals(xRut)) {
                            encontrado = true;
                            nomb = empleado.get(x).getNombre();
                                Mensaje("empleado ya existe => " + nomb.toUpperCase());
                            break; // Terminar ciclo, pues ya lo encontramos
                    }
            }

       // }
        return encontrado;
    }
    
    public void cargaEmpleados(){
        empleado.add(emp1);
        empleado.add(emp2);
        empleado.add(emp3);

        RVentas ok = new RVentas();
        ok.empleado.add(emp1);
        ok.empleado.add(emp2);
        ok.empleado.add(emp3);
        //ok.empleado.add(emp1);
    }
    
    public void Mensaje(String mnsj){
        
        JFrame saje = new JFrame();
        JOptionPane.showMessageDialog(rootPane, mnsj);
        
    }
    public void MuestraAlumos(){
        
        for(int i=0; i <= empleado.size()-1;i ++){
            
             System.out.println("Alumno creado :" + empleado.get(i).getNombre());

        }
        
    }
    
    public void Limpia(){
        jT_Rut.setText("");        
        jT_Nombre.setText("");
        jT_Nombre.setEnabled(false);
        jT_apellido.setText("");
        jT_apellido.setEnabled(false);
        jT_direccion.setText("");
        jT_direccion.setEnabled(false);
        jT_Telefono.setText("");
        jT_Telefono.setEnabled(false);
        jT_Mail.setText("");
        jT_Mail.setEnabled(false);
        jB_RegisEmp.setEnabled(false);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_RegisEmp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jT_DV;
    private javax.swing.JTextField jT_Mail;
    private javax.swing.JTextField jT_Nombre;
    private javax.swing.JTextField jT_Rut;
    private javax.swing.JTextField jT_Telefono;
    private javax.swing.JTextField jT_apellido;
    private javax.swing.JTextField jT_direccion;
    // End of variables declaration//GEN-END:variables

    private void error(String string, Throwable e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
